# Generated by Django 5.2.5 on 2025-08-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_alter_achievement_name_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementemployee',
            name='achievement_date',
            field=models.DateField(auto_now=True),
        ),
    ]
